services:
  pirrtools-dev:
    build: .
    container_name: pirrtools-dev
    volumes:
      - .:/workspace:cached
      - pirrtools-cache:/home/developer/.cache
      - pre-commit-cache:/home/developer/.cache/pre-commit
    working_dir: /workspace
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/workspace
      - PRE_COMMIT_HOME=/home/developer/.cache/pre-commit
    command: /bin/bash -c "/home/developer/.setup-dev.sh && exec /bin/bash"

volumes:
  pirrtools-cache:
  pre-commit-cache: